version: '3.4'

services:
  questdb:
    image: 'questdb/questdb'
    container_name: questdb_alerts
    restart: always
    ports:
      - "8812:8812"
      - "9000:9000"
    networks:
      - "questdb"
    volumes:
      - ./data/db:/root/.questdb/db


  pythontwitterclone:
    image: pythontwitterclone
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
